steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/decentra-vote-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/decentra-vote-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'decentra-vote-app',
           '--image', 'gcr.io/$PROJECT_ID/decentra-vote-app',
           '--platform', 'managed',
           '--region', 'asia-east1',
           '--allow-unauthenticated']
